// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stan.wen9000.domain;

import com.stan.wen9000.domain.AlarmDataOnDemand;
import com.stan.wen9000.domain.AlarmIntegrationTest;
import com.stan.wen9000.domain.AlarmRepository;
import com.stan.wen9000.service.AlarmService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AlarmIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AlarmIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AlarmIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AlarmIntegrationTest: @Transactional;
    
    @Autowired
    private AlarmDataOnDemand AlarmIntegrationTest.dod;
    
    @Autowired
    AlarmService AlarmIntegrationTest.alarmService;
    
    @Autowired
    AlarmRepository AlarmIntegrationTest.alarmRepository;
    
    @Test
    public void AlarmIntegrationTest.testCountAllAlarms() {
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", dod.getRandomAlarm());
        long count = alarmService.countAllAlarms();
        Assert.assertTrue("Counter for 'Alarm' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AlarmIntegrationTest.testFindAlarm() {
        Alarm obj = dod.getRandomAlarm();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to provide an identifier", id);
        obj = alarmService.findAlarm(id);
        Assert.assertNotNull("Find method for 'Alarm' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Alarm' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AlarmIntegrationTest.testFindAllAlarms() {
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", dod.getRandomAlarm());
        long count = alarmService.countAllAlarms();
        Assert.assertTrue("Too expensive to perform a find all test for 'Alarm', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Alarm> result = alarmService.findAllAlarms();
        Assert.assertNotNull("Find all method for 'Alarm' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Alarm' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AlarmIntegrationTest.testFindAlarmEntries() {
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", dod.getRandomAlarm());
        long count = alarmService.countAllAlarms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Alarm> result = alarmService.findAlarmEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Alarm' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Alarm' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AlarmIntegrationTest.testFlush() {
        Alarm obj = dod.getRandomAlarm();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to provide an identifier", id);
        obj = alarmService.findAlarm(id);
        Assert.assertNotNull("Find method for 'Alarm' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAlarm(obj);
        Integer currentVersion = obj.getVersion();
        alarmRepository.flush();
        Assert.assertTrue("Version for 'Alarm' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlarmIntegrationTest.testUpdateAlarmUpdate() {
        Alarm obj = dod.getRandomAlarm();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to provide an identifier", id);
        obj = alarmService.findAlarm(id);
        boolean modified =  dod.modifyAlarm(obj);
        Integer currentVersion = obj.getVersion();
        Alarm merged = alarmService.updateAlarm(obj);
        alarmRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Alarm' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlarmIntegrationTest.testSaveAlarm() {
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", dod.getRandomAlarm());
        Alarm obj = dod.getNewTransientAlarm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Alarm' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Alarm' identifier to be null", obj.getId());
        alarmService.saveAlarm(obj);
        alarmRepository.flush();
        Assert.assertNotNull("Expected 'Alarm' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AlarmIntegrationTest.testDeleteAlarm() {
        Alarm obj = dod.getRandomAlarm();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Alarm' failed to provide an identifier", id);
        obj = alarmService.findAlarm(id);
        alarmService.deleteAlarm(obj);
        alarmRepository.flush();
        Assert.assertNull("Failed to remove 'Alarm' with identifier '" + id + "'", alarmService.findAlarm(id));
    }
    
}
