// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stan.wen9000.domain;

import com.stan.wen9000.domain.CbatDataOnDemand;
import com.stan.wen9000.domain.CbatIntegrationTest;
import com.stan.wen9000.domain.CbatRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CbatIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CbatIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CbatIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CbatIntegrationTest: @Transactional;
    
    @Autowired
    private CbatDataOnDemand CbatIntegrationTest.dod;
    
    @Autowired
    CbatRepository CbatIntegrationTest.cbatRepository;
    
    @Test
    public void CbatIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", dod.getRandomCbat());
        long count = cbatRepository.count();
        Assert.assertTrue("Counter for 'Cbat' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CbatIntegrationTest.testFind() {
        Cbat obj = dod.getRandomCbat();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to provide an identifier", id);
        obj = cbatRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cbat' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cbat' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CbatIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", dod.getRandomCbat());
        long count = cbatRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cbat', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cbat> result = cbatRepository.findAll();
        Assert.assertNotNull("Find all method for 'Cbat' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cbat' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CbatIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", dod.getRandomCbat());
        long count = cbatRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cbat> result = cbatRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Cbat' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cbat' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CbatIntegrationTest.testFlush() {
        Cbat obj = dod.getRandomCbat();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to provide an identifier", id);
        obj = cbatRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cbat' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCbat(obj);
        Integer currentVersion = obj.getVersion();
        cbatRepository.flush();
        Assert.assertTrue("Version for 'Cbat' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CbatIntegrationTest.testSaveUpdate() {
        Cbat obj = dod.getRandomCbat();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to provide an identifier", id);
        obj = cbatRepository.findOne(id);
        boolean modified =  dod.modifyCbat(obj);
        Integer currentVersion = obj.getVersion();
        Cbat merged = cbatRepository.save(obj);
        cbatRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Cbat' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CbatIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", dod.getRandomCbat());
        Cbat obj = dod.getNewTransientCbat(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cbat' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cbat' identifier to be null", obj.getId());
        cbatRepository.save(obj);
        cbatRepository.flush();
        Assert.assertNotNull("Expected 'Cbat' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CbatIntegrationTest.testDelete() {
        Cbat obj = dod.getRandomCbat();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cbat' failed to provide an identifier", id);
        obj = cbatRepository.findOne(id);
        cbatRepository.delete(obj);
        cbatRepository.flush();
        Assert.assertNull("Failed to remove 'Cbat' with identifier '" + id + "'", cbatRepository.findOne(id));
    }
    
}
