// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stan.wen9000.domain;

import com.stan.wen9000.domain.CnuDataOnDemand;
import com.stan.wen9000.domain.CnuIntegrationTest;
import com.stan.wen9000.domain.CnuRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CnuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CnuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CnuIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CnuIntegrationTest: @Transactional;
    
    @Autowired
    private CnuDataOnDemand CnuIntegrationTest.dod;
    
    @Autowired
    CnuRepository CnuIntegrationTest.cnuRepository;
    
    @Test
    public void CnuIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", dod.getRandomCnu());
        long count = cnuRepository.count();
        Assert.assertTrue("Counter for 'Cnu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CnuIntegrationTest.testFind() {
        Cnu obj = dod.getRandomCnu();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to provide an identifier", id);
        obj = cnuRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cnu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cnu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CnuIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", dod.getRandomCnu());
        long count = cnuRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cnu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cnu> result = cnuRepository.findAll();
        Assert.assertNotNull("Find all method for 'Cnu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cnu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CnuIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", dod.getRandomCnu());
        long count = cnuRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cnu> result = cnuRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Cnu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cnu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CnuIntegrationTest.testFlush() {
        Cnu obj = dod.getRandomCnu();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to provide an identifier", id);
        obj = cnuRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cnu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCnu(obj);
        Integer currentVersion = obj.getVersion();
        cnuRepository.flush();
        Assert.assertTrue("Version for 'Cnu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CnuIntegrationTest.testSaveUpdate() {
        Cnu obj = dod.getRandomCnu();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to provide an identifier", id);
        obj = cnuRepository.findOne(id);
        boolean modified =  dod.modifyCnu(obj);
        Integer currentVersion = obj.getVersion();
        Cnu merged = cnuRepository.save(obj);
        cnuRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Cnu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CnuIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", dod.getRandomCnu());
        Cnu obj = dod.getNewTransientCnu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cnu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cnu' identifier to be null", obj.getId());
        cnuRepository.save(obj);
        cnuRepository.flush();
        Assert.assertNotNull("Expected 'Cnu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CnuIntegrationTest.testDelete() {
        Cnu obj = dod.getRandomCnu();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cnu' failed to provide an identifier", id);
        obj = cnuRepository.findOne(id);
        cnuRepository.delete(obj);
        cnuRepository.flush();
        Assert.assertNull("Failed to remove 'Cnu' with identifier '" + id + "'", cnuRepository.findOne(id));
    }
    
}
