// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stan.wen9000.domain;

import com.stan.wen9000.domain.CnuIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CnuIntegrationTest_Roo_Configurable {
    
    declare @type: CnuIntegrationTest: @Configurable;
    
}
